# Generated by Django 4.0.5 on 2022-07-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sd_app', '0005_remove_transaction_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='delivery_date',
            field=models.CharField(max_length=100),
        ),
    ]
