# Generated by Django 3.2.7 on 2022-07-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sd_app', '0008_auto_20220710_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='state',
            field=models.CharField(blank=True, choices=[('tx', 'TX'), ('ca', 'CA'), ('ny', 'NY'), ('fl', 'FL')], max_length=2),
        ),
    ]
