# Generated by Django 3.2.7 on 2022-07-10 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sd_app', '0012_auto_20220710_1501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='address_line_1',
            new_name='address_1',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='address_line_2',
            new_name='address_2',
        ),
    ]
