# Generated by Django 3.2.7 on 2022-07-10 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sd_app', '0013_auto_20220710_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='amount',
            new_name='gallons_requested',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='zip_code',
            new_name='zipcode',
        ),
    ]
