# Generated by Django 3.2.7 on 2022-07-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sd_app', '0015_transaction_suggested_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='total_amount_due',
            field=models.CharField(default='$1,234', max_length=6),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='suggested_price',
            field=models.CharField(default='$4.57', max_length=5),
        ),
    ]
