# Generated by Django 3.2.7 on 2022-07-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sd_app', '0016_auto_20220710_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(max_length=50),
        ),
    ]
