# Generated by Django 3.2.7 on 2022-07-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sd_app', '0018_auto_20220710_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='zipcode',
            field=models.CharField(max_length=9),
        ),
    ]
