# Generated by Django 3.2.7 on 2022-07-10 15:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sd_app', '0019_alter_userprofile_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='zipcode',
            field=models.CharField(max_length=9, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
