# Generated by Django 3.2.7 on 2022-07-10 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sd_app', '0025_alter_transaction_suggested_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='suggested_price',
            field=models.DecimalField(decimal_places=2, default='4.56', max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='total_amount_due',
            field=models.DecimalField(decimal_places=2, default='1234.00', max_digits=10),
        ),
    ]
